Repository operator-framework/operator-registry, pull requests merged in 2019-03, with the labels that each got.

#29 Update docker commands in example to use upstream
  README.md
  upstream-example.Dockerfile
Labels: approved, lgtm, size/XS

#32 Return an error if a CSV specifies a replacement that doesn't exist
  go.mod
  go.sum
  pkg/sqlite/load.go
  vendor/k8s.io/client-go/pkg/version/base.go
Labels: approved, lgtm, size/S

#36 feat(builder): add builder dockerfile
  Dockerfile
  Makefile
  go.mod
  go.sum
  upstream-builder.Dockerfile
  upstream-example.Dockerfile
  vendor/modules.txt
Labels: approved, lgtm, size/M

#35 fixes typos in README.md
  README.md
Labels: approved, lgtm, size/XS

#38 fix references to Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#34 add instructions how to use grpc catalog
  README.md
Labels: approved, lgtm, size/M

#39 update upstream configmap-registry image to use the builder image
  configmap-registry.Dockerfile
Labels: approved, lgtm, size/S

#40 Remove OperatorSource dependency
  cmd/appregistry-server/main.go
  pkg/appregistry/appregistry.go
  pkg/appregistry/downloader.go
  pkg/appregistry/input.go
  pkg/appregistry/opsrc_specifier.go
  pkg/appregistry/registry_specifier.go
  pkg/appregistry/registry_specifier_test.go
  pkg/appregistry/source.go
Labels: approved, lgtm, size/XL

#41 Permit skipping operators during updates
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/server/server_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
Labels: approved, lgtm, size/L
