Repository operator-framework/operator-registry, pull requests merged in 2019-07, with the labels that each got.

#52 [bug] Remove duplicate packages from list
  pkg/appregistry/input.go
  pkg/appregistry/input_test.go
Labels: approved, lgtm, size/S

#54 fix(query): return all channels when querying
  manifests/etcd/etcd.package.yaml
  pkg/server/server_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/query.go
Labels: approved, lgtm, size/M

#55 Bug 1728223: chore(image): change base image to go 1.12
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#56 Bug 1728223: fix(build): don't build static in downstream images
  Dockerfile
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#59 Refactor load/query to remove sqlite json requirement and dependency on OLM
  Makefile
  manifests/etcd/0.9.0/etcdbackup.yaml
  manifests/etcd/0.9.0/etcdcluster.crd.yaml
  manifests/etcd/0.9.0/etcdrestore.crd.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.0.yaml
  pkg/registry/bundle.go
  pkg/registry/csv.go
  pkg/registry/interface.go
  pkg/registry/types.go
  pkg/sqlite/configmap.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
Labels: approved, lgtm, size/XL

#58 feat(load): allow multiple csvs in the same directory
  manifests/etcd/0.9.0/etcdbackup.yaml
  manifests/etcd/0.9.0/etcdcluster.crd.yaml
  manifests/etcd/0.9.0/etcdrestore.crd.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.0.yaml
  pkg/sqlite/directory.go
  pkg/sqlite/load.go
Labels: approved, lgtm, size/M

#60 add dockerfile that just contains the registry server
  registry.Dockerfile
Labels: approved, lgtm, size/S

#61 fix(dockerfile): missing image alias
  registry.Dockerfile
Labels: approved, lgtm, size/XS
