Repository operator-framework/operator-registry, pull requests merged in 2019-01, with the labels that each got.

#16 fix(configmap-server): gvk parsed for owned CRDs incorrectly,
  go.sum
  pkg/sqlite/configmap.go
  pkg/sqlite/configmap_test.go
  vendor/k8s.io/client-go/pkg/version/base.go
Labels: approved, lgtm, size/M

#17 feat(client): expose underlying clients
  pkg/client/client.go
Labels: approved, size/S

#19 fix(bundle): fix CRD conversion with minimum validation field
  go.sum
  pkg/registry/bundle.go
  vendor/k8s.io/client-go/pkg/version/base.go
Labels: approved, lgtm, size/S

#21 Move configmap-server into path
  Dockerfile
  configmap-registry.Dockerfile
Labels: approved, lgtm, size/S

#24 fix(dockerfile): user needs enough access to read from the filesystem
  Dockerfile
Labels: approved, lgtm, size/S
