Repository operator-framework/operator-registry, pull requests merged in 2019-10, with the labels that each got.

#91 Bug 1751388: fix(query): return all channels when querying
  manifests/etcd/etcd.package.yaml
  pkg/server/server_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/query.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#86 pkg/registry: use v1beta1.CustomResourceDefinition, as the apiextensions type is internal
  pkg/registry/bundle.go
Labels: approved, lgtm, size/S

#98 fix(sqlite): enable foreign keys for sqlite
  pkg/sqlite/load.go
Labels: approved, lgtm, size/S

#102 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#103 Image digests for referencing bundles
  pkg/api/conversion.go
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/registry/empty.go
  pkg/registry/interface.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/002_bundle_path.go
  pkg/sqlite/migrations/002_bundle_path_test.go
  pkg/sqlite/query.go
Labels: approved, lgtm, size/L

#97 Add bundle library to build bundle manifest image
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/cmd.go
  cmd/opm/alpha/bundle/generate.go
  cmd/opm/alpha/cmd.go
  cmd/opm/main.go
  docs/design/operator-bundle.md
  pkg/lib/bundle/build.go
  pkg/lib/bundle/build_test.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/utils_test.go
Labels: approved, lgtm, size/XXL

#94 Expose bundle data from bundle image
  cmd/opm/alpha/bundle/cmd.go
  cmd/opm/alpha/bundle/extract.go
  go.mod
  pkg/appregistry/appregistry.go
  pkg/client/kubeclient.go
  pkg/configmap/configmap_writer.go
  test/e2e/bundle_image_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/image-bundle/Dockerfile.bundle
  test/e2e/image-bundle/Dockerfile.serve
  test/e2e/image-bundle/manifests/kiali.crd.yaml
  test/e2e/image-bundle/manifests/kiali.monitoringdashboards.crd.yaml
  test/e2e/image-bundle/manifests/kiali.package.yaml
  test/e2e/image-bundle/manifests/kiali.v1.4.2.clusterserviceversion.yaml
  test/e2e/image-bundle/metadata/annotations.yaml
Labels: approved, lgtm, size/XXL

#107 fix(bundle): Fix manifest directory issue in generated Dockerfile
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, lgtm, size/XS

#108 Add .gitignore based on OLM
  .gitignore
Labels: approved, lgtm, size/L

#92 (feat) Load operator registry bundle from ConfigMap
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/configmap/testdata/bundle-with-all.yaml
  pkg/configmap/testdata/bundle-with-bad-resource.cm.yaml
  pkg/configmap/testdata/bundle-with-kube-resources.cm.yaml
  pkg/configmap/testdata/bundle-with-multiple-csvs.cm.yaml
  pkg/configmap/testdata/bundle.cm.yaml
  pkg/registry/decode.go
  pkg/registry/decode_test.go
  pkg/registry/testdata/invalid-package-manifest.yaml
  pkg/registry/testdata/invalid-unstructured.yaml
  pkg/registry/testdata/valid-package-manifest.yaml
  pkg/registry/testdata/valid-unstructured.yaml
Labels: approved, lgtm, size/XXL

#105 opm registry build / mirror (library only)
  cmd/opm/registry/build.go
  cmd/opm/registry/mirror.go
  glide.yaml
  go.mod
  go.sum
  pkg/appregistry/builder.go
  pkg/appregistry/builder_options.go
  pkg/appregistry/manifest_downloader.go
  pkg/mirror/mirror.go
  pkg/mirror/mirror_test.go
  pkg/mirror/options.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/opencontainers/go-digest/.mailmap
  vendor/github.com/opencontainers/go-digest/.pullapprove.yml
  vendor/github.com/opencontainers/go-digest/.travis.yml
  vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
  vendor/github.com/opencontainers/go-digest/LICENSE.code
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/MAINTAINERS
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/verifiers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#109 fix(bundle): Fix the build parameter order mix-up
  pkg/lib/bundle/build.go
Labels: approved, lgtm, size/XS

#110 feat(imagebuild): add opm binary to registry image build
  Dockerfile
Labels: approved, lgtm, size/XS

#111 feat(sql): extract required apis when loading
  configmap.example.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/registry/conversion.go
  pkg/registry/empty.go
  pkg/registry/interface.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/001_related_images.go
  pkg/sqlite/migrations/001_related_images_test.go
  pkg/sqlite/migrations/002_bundle_path.go
  pkg/sqlite/migrations/003_required_apis.go
  pkg/sqlite/migrations/003_required_apis_test.go
  pkg/sqlite/migrator.go
  pkg/sqlite/query.go
Labels: approved, lgtm, size/XXL

#112 GRPC client wrapper returns api objects
  pkg/client/client.go
Labels: approved, lgtm, size/M
