Repository operator-framework/operator-registry, pull requests merged in 2019-11, with the labels that each got.

#114 fix(configmap): make launch bundle work
  pkg/configmap/configmap_writer.go
Labels: approved, lgtm, size/S

#115 fix(builder): Add AppRegistry org to `ToOption`
  pkg/appregistry/builder_options.go
Labels: approved, lgtm, size/S

#89 Adding OPM cli with registry add and rm commands
  bundles/etcd.0.9.0/manifests/etcdbackup.crd.yaml
  bundles/etcd.0.9.0/manifests/etcdcluster.crd.yaml
  bundles/etcd.0.9.0/manifests/etcdoperator.v0.9.0.yaml
  bundles/etcd.0.9.0/manifests/etcdrestore.crd.yaml
  bundles/etcd.0.9.0/metadata/annotations.yaml
  bundles/etcd.0.9.2/manifests/etcdbackup.crd.yaml
  bundles/etcd.0.9.2/manifests/etcdcluster.crd.yaml
  bundles/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  bundles/etcd.0.9.2/manifests/etcdrestore.crd.yaml
  bundles/etcd.0.9.2/metadata/annotations.yaml
  bundles/prometheus.0.14.0/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.14.0/manifests/prometheus.crd.yaml
  bundles/prometheus.0.14.0/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  bundles/prometheus.0.14.0/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.14.0/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.14.0/metadata/annotations.yaml
  bundles/prometheus.0.15.0/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.15.0/manifests/prometheus.crd.yaml
  bundles/prometheus.0.15.0/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  bundles/prometheus.0.15.0/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.15.0/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.15.0/metadata/annotations.yaml
  bundles/prometheus.0.22.2/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.22.2/manifests/prometheus.crd.yaml
  bundles/prometheus.0.22.2/manifests/prometheusoperator.0.22.2.clusterserviceversion.yaml
  bundles/prometheus.0.22.2/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.22.2/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.22.2/metadata/annotations.yaml
  cmd/opm/registry/add.go
  cmd/opm/registry/cmd.go
  cmd/opm/registry/rm.go
  cmd/opm/registry/serve.go
  pkg/containertools/bundlereader.go
  pkg/containertools/command.go
  pkg/registry/bundle.go
  pkg/registry/interface.go
  pkg/registry/types.go
  pkg/sqlite/directory.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/004_cascade_delete.go
  pkg/sqlite/migrations/004_cascade_delete_test.go
  pkg/sqlite/remove.go
  pkg/sqlite/remove_test.go
Labels: approved, lgtm, size/XXL

#113 feat(api): return version and skiprange in bundle
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/mirror/mirror.go
  pkg/mirror/mirror_test.go
  pkg/sqlite/migrations/000_init.go
  pkg/sqlite/migrations/001_related_images.go
  pkg/sqlite/migrations/002_bundle_path.go
  pkg/sqlite/migrations/003_required_apis.go
  pkg/sqlite/migrations/003_required_apis_test.go
  pkg/sqlite/migrations/004_cascade_delete.go
  pkg/sqlite/migrations/005_version_skiprange.go
  pkg/sqlite/migrations/005_version_skiprange_test.go
  pkg/sqlite/migrations/migrations.go
  pkg/sqlite/migrator.go
  pkg/sqlite/query.go
Labels: approved, lgtm, size/L

#118 fix(configmap): bump base image for configmap registry image
  configmap-registry.Dockerfile
Labels: approved, lgtm, size/XS

#121 Make imagereader work for all layer paths
  pkg/containertools/containertoolsfakes/fake_image_reader.go
  pkg/containertools/getimagedata_options.go
  pkg/containertools/imagereader.go
  pkg/containertools/imagereader_test.go
  pkg/containertools/testdata/docker/bundle.tar
  pkg/containertools/testdata/expected_unpack/manifests/alertmanager.crd.yaml
  pkg/containertools/testdata/expected_unpack/manifests/prometheus.crd.yaml
  pkg/containertools/testdata/expected_unpack/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/containertools/testdata/expected_unpack/manifests/prometheusrule.crd.yaml
  pkg/containertools/testdata/expected_unpack/manifests/servicemonitor.crd.yaml
  pkg/containertools/testdata/expected_unpack/metadata/annotations.yaml
  pkg/containertools/testdata/podman/bundle.tar
  pkg/lib/indexer/indexer.go
Labels: approved, lgtm, size/XXL

#122 Bug 1771522: add version and skiprange to operatorbundle table
  configmap.example.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/bundle.go
  pkg/registry/csv.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#126 fix(e2e): update ginkgo configmap test
  test/e2e/bundle_image_test.go
  test/e2e/image-bundle/Dockerfile.serve
Labels: approved, lgtm, size/M

#124 Bug 1771273: Fix bundle build command with Docker and update documentation
  docs/design/operator-bundle.md
  pkg/lib/bundle/build.go
  pkg/lib/bundle/build_test.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#127 Bug 1771273: Ensure provided directory has at least one yaml manifest file
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  docs/design/operator-bundle.md
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#125 Bug 1771850: Error logging for opm alpha bundle extract command
  go.mod
  go.sum
  pkg/configmap/configmap_writer.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#128 Bug 1774630: Fix panic caused by incorrect bundle data
  incorrectbundle/3scale-community-operator/0.3.0/3scale-community-operator.v0.3.0.clusterserviceversion.yaml
  incorrectbundle/3scale-community-operator/0.3.0/apimanagers.apps.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/apis.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/bindings.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/limits.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/mappingrules.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/metrics.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/plans.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/0.3.0/tenants.capabilities.3scale.net.crd.yaml
  incorrectbundle/3scale-community-operator/3scale-community-operator.package.yaml
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#129 Bug 1774630: relocate test data
  pkg/sqlite/directory_test.go
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/3scale-community-operator.v0.3.0.clusterserviceversion.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/apimanagers.apps.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/apis.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/bindings.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/limits.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/mappingrules.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/metrics.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/plans.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/0.3.0/tenants.capabilities.3scale.net.crd.yaml
  pkg/sqlite/testdata/incorrectbundle/3scale-community-operator/3scale-community-operator.package.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#130 Bug 1775527: Fix ignored cachedir in appregistry image builder
  Makefile
  go.sum
  pkg/apprclient/apprclientfakes/fake_client.go
  pkg/apprclient/client.go
  pkg/appregistry/appregistry_suite_test.go
  pkg/appregistry/appregistryfakes/fake_image_appender.go
  pkg/appregistry/appregistryfakes/fake_manifest_downloader.go
  pkg/appregistry/builder.go
  pkg/appregistry/builder_options.go
  pkg/appregistry/builder_test.go
  pkg/appregistry/manifest_downloader.go
  pkg/appregistry/testdata/golden/marsupials_pkg.tar
  pkg/containertools/command.go
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/imagereader.go
  pkg/containertools/labelreader.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/registry/interfaces.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL
