Repository operator-framework/operator-registry, pull requests merged in 2019-08, with the labels that each got.

#69 Bug 1732579: Best-effort loading
  .gitignore
  cmd/appregistry-server/main.go
  go.mod
  go.sum
  pkg/appregistry/appregistry.go
  pkg/registry/bundle.go
  pkg/registry/empty.go
  pkg/registry/types.go
  pkg/sqlite/configmap.go
  pkg/sqlite/directory.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/testdata/.gitignore
  vendor/github.com/otiai10/copy/.gitignore
  vendor/github.com/otiai10/copy/.travis.yml
  vendor/github.com/otiai10/copy/LICENSE
  vendor/github.com/otiai10/copy/README.md
  vendor/github.com/otiai10/copy/copy.go
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#72 Fix early load exit for unpacked appregistry format
  manifests/strimzi-kafka-operator/Kafka-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaBridge-v1alpha1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaConnect-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaConnectS2I-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaMirrorMaker-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaTopic-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/KafkaUser-v1beta1.crd.yaml
  manifests/strimzi-kafka-operator/strimzi-cluster-operator.v0.11.0.clusterserviceversion.yaml
  manifests/strimzi-kafka-operator/strimzi-cluster-operator.v0.11.1.clusterserviceversion.yaml
  manifests/strimzi-kafka-operator/strimzi-cluster-operator.v0.12.1.clusterserviceversion.yaml
  manifests/strimzi-kafka-operator/strimzi-cluster-operator.v0.12.2.clusterserviceversion.yaml
  manifests/strimzi-kafka-operator/strimzi-kafka-operator.package.yaml
  pkg/server/server_test.go
  pkg/sqlite/directory.go
  pkg/sqlite/directory_test.go
Labels: approved, lgtm, size/XXL

#74 Permissive/Strict Options
  cmd/appregistry-server/main.go
  cmd/configmap-server/main.go
  cmd/initializer/main.go
  cmd/registry-server/main.go
Labels: approved, lgtm, size/L

#75 fix(registry) Fix incorrect error return and handle
  pkg/schema/schema.go
Labels: approved, lgtm, size/XS

#84 Bug 1745946: fix(sqlite): defer rollbacks to prevent db lock
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
