Repository operator-framework/operator-registry, pull requests merged in 2020-07, with the labels that each got.

#346 feat: add pdb, vpa, and priorityclass object support to registry
  pkg/lib/bundle/supported_resources.go
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdpdb.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdpriorityclass.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdvpa.yaml
Labels: approved, lgtm

#374 Separate build/pull tool for index rm
  cmd/opm/index/delete.go
  pkg/lib/indexer/interfaces.go
Labels: approved, lgtm

#375 Update OPM_VERSION
  OPM_VERSION
Labels: approved

#363 feat(store): store provided apis as generic "properties"
  Makefile
  bundles/etcd.0.9.2/metadata/dependencies.yaml
  bundles/prometheus.0.22.2/metadata/dependencies.yaml
  cmd/registry-server/main.go
  docs/design/operator-bundle.md
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/metadata/dependencies.yaml
  pkg/lib/bundle/validate.go
  pkg/lib/bundle/validate_test.go
  pkg/registry/bundle.go
  pkg/registry/imageinput.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/types.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle_test.go
  pkg/sqlite/migrations/009_properties.go
  pkg/sqlite/migrations/009_properties_test.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#361 Use /. as the directory root to copy from.
  pkg/image/execregistry/registry.go
Labels: approved, lgtm, ok-to-test

#300 fix(opm): refactor indexer
  pkg/image/containerdregistry/registry.go
  pkg/lib/bundle/exporter.go
  pkg/lib/indexer/indexer.go
Labels: approved, lgtm, triage/unresolved

#378 feat(release): add builds for s390x and ppc64le
  .travis.yml
Labels: approved, lgtm

#379 Bump GRPC version
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm, ok-to-test

#380 pkg/lib/bundle/generate.go: add JSON tag to AnnotationMetadata
  pkg/lib/bundle/generate.go
Labels: approved, lgtm

#381 feat(api): add skips/replaces to listbundles api
  Makefile
  codegen.Dockerfile
  go.mod
  go.sum
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/grpc_health_v1/health.proto
  pkg/api/grpc_health_v1/health_grpc.pb.go
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/api/registry_grpc.pb.go
  pkg/server/health.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/sqlite/query.go
  tools.go
  vendor/github.com/golang/protobuf/protoc-gen-go/main.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_references.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/LICENSE
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/README.md
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/go.mod
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/go.sum
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/grpc.go
  vendor/google.golang.org/grpc/cmd/protoc-gen-go-grpc/main.go
  vendor/google.golang.org/protobuf/cmd/protoc-gen-go/main.go
  vendor/modules.txt
Labels: approved, lgtm

#382 fix(build): don't set -race when testing on s390x
  Makefile
Labels: approved, lgtm

#388 Use go env to get architecture for building
  Makefile
Labels: approved, lgtm, ok-to-test

#390 Bug 1857502: fix(validate): pull bundle images before unpacking
  pkg/image/containerdregistry/options.go
  pkg/lib/bundle/validate.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#384 Check before insert
  cmd/opm/main.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/types.go
Labels: approved, lgtm

#392 Update OPM_VERSION
  OPM_VERSION
Labels: approved

#391 Add GetPackage to the client interface.
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, lgtm

#393 Embed version at link time based on git tags instead of a file.
  Dockerfile
  Makefile
  OPM_VERSION
  docs/contributors/releases.md
Labels: approved, lgtm

#394 Remove nonexistent group from Dockerfile
  Dockerfile
Labels: approved, lgtm, ok-to-test

#399 Remove unneeded static dependencies
  Dockerfile
  Makefile
Labels: approved, lgtm

#405 Fix listbundles property bug
  pkg/sqlite/query.go
Labels: approved, lgtm

#408 fix(validation): Remove default channel validation from bundle lib
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/validate.go
Labels: approved, lgtm

#397 Adding ability to deprecate bundles
  bundles/etcd.0.9.0/metadata/annotations.yaml
  cmd/opm/index/cmd.go
  cmd/opm/index/deprecate.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/registry/interfaces.go
  pkg/lib/registry/registry.go
  pkg/registry/interface.go
  pkg/registry/populator_test.go
  pkg/registry/types.go
  pkg/sqlite/deprecate.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/query.go
Labels: approved, area/dependency, lgtm

#406 feat(registry): Add label dependency constraint and property
  docs/design/operator-bundle.md
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/manifests/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/manifests/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/manifests/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/metadata/annotations.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/metadata/dependencies.yaml
  pkg/lib/bundle/validate.go
  pkg/lib/bundle/validate_test.go
  pkg/registry/types.go
  pkg/server/server_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
Labels: approved, area/dependency, lgtm

#370 Add timeout to opm registry serve
  Makefile
  cmd/opm/registry/serve.go
Labels: approved, lgtm, ok-to-test
