Repository operator-framework/operator-registry, pull requests merged in 2020-06, with the labels that each got.

#335 docs: remove typo from operator-bundle dependencies example
  docs/design/operator-bundle.md
Labels: approved, lgtm, ok-to-test

#333 chore: fixed a typo in bundle manifest format description
  docs/design/operator-bundle.md
Labels: approved, lgtm, ok-to-test

#319 fix: add err check before defer
  pkg/sqlite/load.go
Labels: approved, lgtm, ok-to-test

#296 add info over where the bundle files are or will be written
  pkg/lib/bundle/generate.go
Labels: approved, lgtm

#347 [e2e] Fix opm test
  test/e2e/opm_test.go
Labels: approved, lgtm

#210 upstream-builder: update grpc-health-probe version
  registry.Dockerfile
  upstream-builder.Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#350 Update OWNERS
  OWNERS
Labels: approved, lgtm

#351 fix(images): use docker/podman create and cp for exec unpacking
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  cmd/opm/alpha/bundle/validate.go
  manifests/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/containertools/containertoolsfakes/fake_image_reader.go
  pkg/containertools/imagereader.go
  pkg/containertools/imagereader_test.go
  pkg/containertools/runner.go
  pkg/image/execregistry/registry.go
  pkg/image/registry_test.go
  pkg/lib/bundle/interfaces.go
  pkg/lib/bundle/validate.go
  pkg/lib/bundle/validate_test.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  test/e2e/opm_test.go
Labels: approved, lgtm

#358 pkg/lib/bundle/generate.go: do not compare number of annotations
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, lgtm

#356 Bug 1846100: fix(server): make a copy of the db before migrating it
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/lib/tmp/copy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#360 Fix broken link to CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, ok-to-test

#119 test(server): wait for connection to go healthy before running tests
  pkg/server/server_test.go
Labels: approved, lgtm, size/XS, triage/unresolved

#270 Add BugZilla component to OWNERS file
  OWNERS
Labels: approved, lgtm, triage/unresolved

#372 Update OPM version to 1.12.6
  OPM_VERSION
Labels: approved, lgtm

#373 (fix) Update to go 1.14
  Dockerfile
Labels: approved, lgtm
