Repository operator-framework/operator-registry, pull requests merged in 2020-12, with the labels that each got.

#524 Bug 1902803: Reconstruct replaces/splits for Listbundles from channel_entry.
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#527 Bug 1895367: Include the bundle image itself as a related image.
  pkg/registry/bundle.go
  pkg/registry/bundle_test.go
  pkg/registry/populator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#528 Bug 1902824: fix(index): account for default channel in index add order
  pkg/registry/input_stream.go
  pkg/registry/input_stream_test.go
  pkg/registry/populator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#530 Disable broken ppc64le and s390x release builds.
  .github/workflows/release.yaml
Labels: approved, lgtm

#531 Bug 1883560: Avoid duplicate registry binaries across downstream image layers.
  Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#521 [release-4.6] Bug 1898746: fix(indexing): order bulk add by version field
  bundles/prometheus.0.14.0-beta/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  cmd/opm/index/add.go
  go.mod
  go.sum
  pkg/containertools/containertoolsfakes/fake_command_runner.go
  pkg/lib/bundle/validate.go
  pkg/lib/indexer/indexerfakes/fake_index_exporter.go
  pkg/lib/validation/bundle_test.go
  pkg/registry/bundle.go
  pkg/registry/bundle_test.go
  pkg/registry/decode.go
  pkg/registry/empty.go
  pkg/registry/imageinput.go
  pkg/registry/input_stream.go
  pkg/registry/input_stream_test.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/registryfakes/fake_graph_loader.go
  pkg/registry/replacesgraphloader.go
  pkg/sqlite/configmap.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/query.go
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#536 chore: move upstream tests from travisCI
  .github/workflows/test.yml
  .github/workflows/unit.yaml
  .travis.yml
  docs/contributors/releases.md
  test/e2e/bundle_image_test.go
Labels: approved, lgtm
