Repository operator-framework/operator-registry, pull requests merged in 2020-01, with the labels that each got.

#135 Fix tiny typo
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#63 Bug 1783030: Detect replacement cycles while adding package channels
  pkg/sqlite/configmap_test.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#145 fix(bundle): set csv name field on configmap loading
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
Labels: approved, lgtm, size/XS

#147 fix(build): grpc-health-probe was not building properly in 1.13
  Dockerfile
Labels: approved, lgtm, size/XS

#155 Build binaries for linux, windows, and mac
  .travis.yml
  Dockerfile
  Makefile
  appr-registry.Dockerfile
  configmap-registry.Dockerfile
  docs/contributors/releases.md
  opm-example.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-example.Dockerfile
Labels: approved, lgtm, size/L

#156 Fix issue with empty docker error output
  pkg/containertools/command.go
Labels: approved, lgtm, size/M

#158 chore(release): use robot for deploys
  .travis.yml
  Dockerfile
  Makefile
  README.md
  appr-registry.Dockerfile
  configmap-registry.Dockerfile
  docs/contributors/releases.md
  opm-example.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
Labels: approved, lgtm, size/M

#141 Add support for choosing the release of a package
  cmd/appregistry-server/main.go
  go.sum
  pkg/apprclient/client.go
  pkg/apprclient/metadata.go
  pkg/appregistry/downloader.go
  pkg/appregistry/downloader_test.go
  pkg/appregistry/input.go
  pkg/appregistry/input_test.go
Labels: approved, lgtm, ok-to-test, size/L

#153 Bug 1784028: Updating summary for 'Operator Registry ' containers
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#149 Add `opm` docs
  README.md
  docs/design/opm-tooling.md
Labels: approved, lgtm, size/L

#160 fix(ci): build opm statically in CI
  Dockerfile
Labels: approved, lgtm, size/XS

#154 Index maintainers can export a package from an index
  Makefile
  bundles/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  cmd/opm/index/cmd.go
  cmd/opm/index/export.go
  docs/design/opm-tooling.md
  go.sum
  opm-test.sh
  pkg/lib/bundle/exporter.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/indexer_test.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/indexer/test/bundles.db
  pkg/lib/indexer/test/package.yaml
  pkg/lib/registry/registry.go
  pkg/registry/empty.go
  pkg/registry/interface.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/load.go
  pkg/sqlite/query.go
Labels: approved, lgtm, size/XL

#162 Bug 1795237: Revert "fix(ci): build opm statically in CI"
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#163 Bug 1795297: Fixing wrong database loaded in memory for export cmd
  opm-test.sh
  pkg/lib/indexer/indexer.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#166 Add validate bundle test cases
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle_2/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle_2/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle_2/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle_2/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/validate_test.go
Labels: approved, lgtm, size/XL

#148 Bug 1790785: feat(appr): exit build early if no manifests were downloaded
  pkg/appregistry/builder.go
  pkg/appregistry/builder_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
