Repository operator-framework/operator-registry, pull requests merged in 2020-04, with the labels that each got.

#241 [feature] Understanding packages from bundle directory
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  go.sum
  pkg/lib/bundle/build.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/interpreter.go
  pkg/lib/bundle/interpreter_test.go
  pkg/registry/csv.go
  pkg/registry/csv_test.go
  pkg/registry/directoryGraphLoader.go
  pkg/registry/directoryGraphLoader_test.go
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apimanagers.apps.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apis.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/bindings.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/limits.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/mappingrules.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/metrics.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/plans.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/tenants.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/3scale-community-operator.package.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/etcd.package.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/prometheus.package.yaml
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/modules.txt
Labels: approved, lgtm

#236 fix(loader): Image Loader doesn't create the same channel entries as the other loaders.
  bundles/prometheus.0.15.0/metadata/annotations.yaml
  cmd/opm/index/delete.go
  cmd/opm/registry/add.go
  cmd/opm/registry/mirror.go
  cmd/opm/registry/rm.go
  pkg/containertools/getimagedata_options.go
  pkg/containertools/labelreader_test.go
  pkg/mirror/mirror.go
  pkg/mirror/mirror_test.go
  pkg/registry/bundle.go
  pkg/registry/interface.go
  pkg/server/server_test.go
  pkg/sqlite/configmap.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/graphloader.go
  pkg/sqlite/graphloader_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/migrations/003_required_apis.go
  pkg/sqlite/migrations/003_required_apis_test.go
  pkg/sqlite/migrations/005_version_skiprange.go
  pkg/sqlite/migrations/005_version_skiprange_test.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle_test.go
  pkg/sqlite/migrations/007_replaces_skips.go
  pkg/sqlite/migrations/007_replaces_skips_test.go
  pkg/sqlite/migrator.go
  pkg/sqlite/migrator_test.go
  pkg/sqlite/query.go
  pkg/sqlite/remove.go
  pkg/sqlite/remove_test.go
Labels: approved, lgtm

#242 fix the `validate` command in the docs
  docs/design/operator-bundle.md
Labels: approved, lgtm, ok-to-test

#248 Fix panic in registry add
  pkg/registry/populator.go
Labels: approved, lgtm

#253 chore(travis): add conntrack package
  .travis.yml
Labels: approved, lgtm

#247 Semver index insert
  cmd/opm/index/add.go
  cmd/opm/registry/add.go
  pkg/lib/bundle/validate.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  pkg/registry/bundle.go
  pkg/registry/bundlegraphloader.go
  pkg/registry/bundlegraphloader_test.go
  pkg/registry/channelupdateoptions.go
  pkg/registry/empty.go
  pkg/registry/graph.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/types.go
  pkg/sqlite/configmap.go
  pkg/sqlite/graphloader.go
  pkg/sqlite/graphloader_test.go
  pkg/sqlite/image_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/loadprocs.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#260 fix(imageloader): image loader should consider existing channels during add
  bundles/prometheus.0.14.0-beta/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.14.0-beta/manifests/prometheus.crd.yaml
  bundles/prometheus.0.14.0-beta/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  bundles/prometheus.0.14.0-beta/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.14.0-beta/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.14.0-beta/metadata/annotations.yaml
  pkg/lib/registry/registry.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/sqlite/image.go
  pkg/sqlite/remove_test.go
Labels: approved, lgtm

#251 bug(opm): packages flag on registry rm required
  cmd/opm/registry/rm.go
Labels: approved, lgtm, ok-to-test

#256 feat: generate a bundle with configmap and secret objects
  pkg/lib/bundle/supported_resources.go
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdconfigmap.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdsecret.yaml
Labels: approved, lgtm

#262 test(e2e): login w/ docker first to prevent failures
  test/e2e/e2e_suite_test.go
  test/e2e/opm_test.go
Labels: approved, lgtm

#265 fix(load): shouldn't clear bundle/csv field from non-default heads
  bundles/prometheus.0.15.0-stable/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.15.0-stable/manifests/prometheus.crd.yaml
  bundles/prometheus.0.15.0-stable/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  bundles/prometheus.0.15.0-stable/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.15.0-stable/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.15.0-stable/metadata/annotations.yaml
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
Labels: approved, lgtm

#254 feat(registry): Add operator version dependency metadata
  bundles/etcd.0.9.2/metadata/dependencies.yaml
  bundles/prometheus.0.22.2/metadata/dependencies.yaml
  docs/design/operator-bundle.md
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/registry/bundle.go
  pkg/registry/empty.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/types.go
  pkg/server/server.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/008_dependencies.go
  pkg/sqlite/migrations/008_dependencies_test.go
  pkg/sqlite/query.go
Labels: approved, do-not-merge/hold, lgtm

#244 bug(opm): use db dir when modifying existing index
  pkg/lib/indexer/indexer.go
  test/e2e/opm_test.go
Labels: approved, lgtm, ok-to-test

#279 fix(add): allow containertool to be specified for registry add
  cmd/opm/index/add.go
  cmd/opm/index/delete.go
  cmd/opm/index/export.go
  cmd/opm/registry/add.go
  pkg/containertools/command.go
  pkg/containertools/containertool.go
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/imagereader.go
  pkg/containertools/labelreader.go
  pkg/image/containerdregistry/options.go
  pkg/image/containerdregistry/registry.go
  pkg/image/containerdregistry/resolver.go
  pkg/image/execregistry/registry.go
  pkg/image/registry.go
  pkg/image/registry_test.go
  pkg/lib/bundle/exporter.go
  pkg/lib/bundle/interfaces.go
  pkg/lib/image/registry.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/registry/registry.go
  test/e2e/opm_test.go
Labels: approved, lgtm

#280 fix(registry): Fix dependency load/query and add ListBundles to registry client
  configmap.example.yaml
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/types.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/008_dependencies.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#281 fix(index-add): docker index add failing
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
  pkg/lib/indexer/indexer.go
Labels: approved, lgtm

#284 Fix panic in AddToRegistry when using podman.
  pkg/lib/registry/registry.go
Labels: approved, lgtm

#285 (feat): Bundle commutativity
  pkg/lib/registry/registry.go
  pkg/registry/graph.go
  pkg/registry/imageinput.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/replacesgraphloader.go
  pkg/sqlite/remove_test.go
Labels: approved, lgtm

#277 Add dependencies validation to opm
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/manifests/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/manifests/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/manifests/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/metadata/annotations.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/manifests/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/manifests/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/manifests/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/metadata/annotations.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/manifests/etcdbackups.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/manifests/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/manifests/etcdrestores.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/metadata/annotations.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/metadata/dependencies.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/metadata/dependencies.yaml
  pkg/lib/bundle/validate.go
  pkg/lib/bundle/validate_test.go
  pkg/registry/imageinput.go
  pkg/registry/populator.go
  pkg/registry/types.go
Labels: approved, lgtm

#283 Bug 1825925: support deamonless export
  cmd/opm/index/export.go
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
  pkg/image/containerdregistry/registry.go
  pkg/image/execregistry/registry.go
  pkg/image/registry.go
  pkg/lib/bundle/exporter.go
  pkg/lib/indexer/indexer.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#299 Bug 1827906: (fix) Use opm builder image for opm indexes
  configmap-registry.Dockerfile
  docs/design/opm-tooling.md
  opm-example.Dockerfile
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
  upstream-builder.Dockerfile
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#243 bug 1827748: feature: opm (index|registry) prune command
  cmd/opm/index/cmd.go
  cmd/opm/index/prune.go
  cmd/opm/registry/cmd.go
  cmd/opm/registry/prune.go
  docs/design/opm-tooling.md
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/registry/interfaces.go
  pkg/lib/registry/registry.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm, ok-to-test

#289 Bug 1826766: fix(types): Fix GetDependencies func that returns duplicate items
  bundles/prometheus.0.22.2/metadata/dependencies.yaml
  pkg/registry/populator_test.go
  pkg/registry/types.go
Labels: approved, bugzilla/severity-low, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#312 Bug 1827992: Clarify log message to indicate that dependencies.yaml is optional.
  pkg/lib/bundle/validate.go
  pkg/registry/imageinput.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
