Repository operator-framework/operator-registry, pull requests merged in 2020-09, with the labels that each got.

#430 Bug 1875557: add mac and windows binaries to the amd64 build
  Dockerfile
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#435 Bug 1875557: fix(bin): don't overwrite /bin
  Dockerfile
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#437 Bug 1877603: add workdir permissions back
  Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#442 disable cross compilation while build issues are resolved
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#443 Bug 1875557: add cross build back
  Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#439 Use multi-stage build for registry image.
  upstream-builder.Dockerfile
Labels: approved, lgtm

#400 [release-4.5] Bug 1845588: fix(images): use docker/podman create and cp for exec unpacking
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  cmd/opm/alpha/bundle/validate.go
  manifests/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/containertools/containertoolsfakes/fake_image_reader.go
  pkg/containertools/imagereader.go
  pkg/containertools/imagereader_test.go
  pkg/containertools/runner.go
  pkg/image/containerdregistry/options.go
  pkg/image/execregistry/registry.go
  pkg/image/registry_test.go
  pkg/lib/bundle/interfaces.go
  pkg/lib/bundle/validate.go
  pkg/lib/bundle/validate_test.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#429 Bug 1880127: Parallelize opm index export
  cmd/opm/index/export.go
  pkg/lib/bundle/exporter.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/indexer_test.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#416 Add test to verify empty bundles in addition does not break
  cmd/opm/index/add.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#448 Bug 1880501: Adding overwrite-latest flag to index add
  cmd/opm/index/add.go
  cmd/opm/registry/add.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  pkg/registry/bundle.go
  pkg/registry/empty.go
  pkg/registry/imageinput.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/replacesgraphloader.go
  pkg/registry/testdata/overwrite/etcd.0.9.0/manifests/etcdbackup.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.0/manifests/etcdcluster.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.0/manifests/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.0/manifests/etcdrestore.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.0/metadata/annotations.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/manifests/etcdbackup.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/manifests/etcdcluster.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/manifests/etcdrestore.crd.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/metadata/annotations.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/metadata/dependencies.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/manifests/alertmanager.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/manifests/prometheus.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/manifests/prometheusrule.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/manifests/servicemonitor.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.15.0/metadata/annotations.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/manifests/alertmanager.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/manifests/prometheus.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/manifests/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/manifests/prometheusrule.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/manifests/servicemonitor.crd.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/metadata/annotations.yaml
  pkg/registry/testdata/overwrite/prometheus.0.22.2/metadata/dependencies.yaml
  pkg/registry/types.go
  pkg/sqlite/graphloader.go
  pkg/sqlite/query.go
  pkg/sqlite/remove_test.go
  pkg/sqlite/stranded_test.go
  test/e2e/opm_test.go
  test/e2e/testdata/aqua/1.0.1-overwrite/aqua-operator.v1.0.1.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#455 Bug 1882479: erroring when replacement not found
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/replacesgraphloader.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#451 Bug 1878213: Update index add func to handle optional default channel
  docs/design/operator-bundle.md
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/validate.go
  pkg/registry/populator.go
  pkg/registry/types.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#458 Bug 1882807: bundle inference should not use skiprange
  pkg/registry/directoryGraphLoader.go
  pkg/registry/directoryGraphLoader_test.go
  pkg/registry/testdata/validPackages/aqua/0.0.1/aqua-operator.v0.0.1.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquacsps.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquadatabases.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquaenforcers.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquagateways.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquascanners.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/0.0.1/aquaservers.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aqua-operator.v1.0.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquacsps.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquadatabases.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquaenforcers.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquagateways.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquascanners.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/1.0.0/aquaservers.operator.aquasec.com.crd.yaml
  pkg/registry/testdata/validPackages/aqua/aqua-operator.package.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#459 Bug 1883329: Bundle validation shouldn't fail if default channel is not provided
  pkg/lib/bundle/testdata/validate/invalid_annotations_bundle/metadata/annotations.yaml
  pkg/lib/bundle/validate.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
