Repository operator-framework/operator-registry, pull requests merged in 2020-08, with the labels that each got.

#410 fix(query): return bundles in all channels
  pkg/registry/populator_test.go
  pkg/server/server_test.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#404 feat(registry): add graceful shutdown to grpc server
  cmd/appregistry-server/main.go
  cmd/configmap-server/main.go
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/lib/graceful/shutdown.go
Labels: approved, lgtm

#411 [docs] Update out of date compile step
  docs/design/operator-bundle.md
Labels: approved, lgtm

#413 Bug 1866930: Clean up stranded bundles
  cmd/opm/index/cmd.go
  cmd/opm/index/prunestranded.go
  cmd/opm/registry/cmd.go
  cmd/opm/registry/prunestranded.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  pkg/lib/registry/interfaces.go
  pkg/lib/registry/registry.go
  pkg/registry/interface.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/010_set_bundlepath_pkg_property.go
  pkg/sqlite/migrations/010_set_bundlepath_pkg_property_test.go
  pkg/sqlite/stranded.go
  pkg/sqlite/stranded_test.go
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/manifests/alertmanager.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/manifests/prometheus.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/manifests/prometheusrule.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/manifests/servicemonitor.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.14.0/metadata/annotations.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/manifests/alertmanager.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/manifests/prometheus.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/manifests/prometheusrule.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/manifests/servicemonitor.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.15.0/metadata/annotations.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/manifests/alertmanager.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/manifests/prometheus.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/manifests/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/manifests/prometheusrule.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/manifests/servicemonitor.crd.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/metadata/annotations.yaml
  pkg/sqlite/testdata/strandedbundles/prometheus.0.22.2/metadata/dependencies.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#417 Bug 1867848: Return empty properties and dependencies in ListBundles responses.
  go.mod
  pkg/sqlite/query.go
  pkg/sqlite/query_test.go
  pkg/sqlite/sqlitefakes/fake_querier.go
  pkg/sqlite/sqlitefakes/fake_rowscanner.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#420 Remove label dependency from bundle docs.
  docs/design/operator-bundle.md
Labels: approved, lgtm

#419 Fix typos
  docs/design/operator-bundle.md
Labels: approved, lgtm, ok-to-test

#422 Bug 1870378: add quotes to semver range example
  docs/design/operator-bundle.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#402 Bug 1866437: skip TLS option for pulling indexes
  cmd/opm/index/add.go
  cmd/opm/index/cmd.go
  cmd/opm/index/delete.go
  cmd/opm/index/deprecate.go
  cmd/opm/index/export.go
  cmd/opm/index/prune.go
  cmd/opm/index/prunestranded.go
  cmd/opm/registry/add.go
  go.sum
  pkg/containertools/runner.go
  pkg/image/execregistry/registry.go
  pkg/lib/certs/certs.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  tools.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#427 Update OWNERS
  OWNERS
Labels: approved

#421 Bug 1873483: fixing typo in deprecatetruncate command
  cmd/opm/index/deprecatetruncate.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
