Repository operator-framework/operator-registry, pull requests merged in 2020-03, with the labels that each got.

#206 Match bundle image directory structure
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  docs/design/operator-bundle.md
  pkg/lib/bundle/build.go
  pkg/lib/bundle/build_test.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/testdata/generate/manifests/alertmanager.crd.yaml
  pkg/lib/bundle/testdata/generate/manifests/prometheus.crd.yaml
  pkg/lib/bundle/testdata/generate/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/generate/manifests/prometheusrule.crd.yaml
  pkg/lib/bundle/testdata/generate/manifests/servicemonitor.crd.yaml
  pkg/lib/bundle/testdata/generate/nested_manifests/alertmanager.crd.yaml
  pkg/lib/bundle/testdata/generate/nested_manifests/more_manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/generate/nested_manifests/prometheus.crd.yaml
  pkg/lib/bundle/testdata/generate/nested_manifests/prometheusrule.crd.yaml
  pkg/lib/bundle/testdata/generate/nested_manifests/servicemonitor.crd.yaml
Labels: approved, lgtm, size/XXL

#164 Update operator-registry OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#193 Update go.mod to remove unneeded license dependency
  go.mod
  go.sum
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#209 Generalize manifest copy
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, lgtm, size/XS

#169 Bug 1794176: Updating summary for 'Operator Registry ' containers
  Dockerfile
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/XS

#196 Opm test
  .travis.yml
  Makefile
  go.sum
  opm-test.sh
  pkg/containertools/imagereader.go
  pkg/lib/registry/registry.go
  test/e2e/bundle_image_test.go
  test/e2e/opm_test.go
  tools.go
  vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/build_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/ginkgo_ast_nodes.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/import.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/package_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/test_finder.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testfile_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testing_t_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/help_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/interrupt_handler.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_unix.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_windows.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot/nodot.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/notifications.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_watch_and_build_command_flags.go
  vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args_old.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/log_writer.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/run_result.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/test_suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go15.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go16.go
  vendor/github.com/onsi/ginkgo/ginkgo/unfocus_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/version_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta_tracker.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hashes.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch_command.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#224 Graph Loader initial implementation
  go.mod
  pkg/registry/empty.go
  pkg/registry/graph.go
  pkg/registry/interface.go
  pkg/registry/types.go
  pkg/sqlite/graphloader.go
  pkg/sqlite/graphloader_test.go
  pkg/sqlite/query.go
  pkg/sqlite/test.txt
  pkg/sqlite/testdata/loader_data/etcd/0.6.1/etcdcluster.crd.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdbackup.crd.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdcluster.crd.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdoperator.v0.9.0.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdrestore.crd.yaml
  pkg/sqlite/testdata/loader_data/etcd/etcd.package.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.14.0/prometheus.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.14.0/prometheusrule.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.14.0/servicemonitor.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.15.0/prometheus.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.15.0/prometheusrule.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.15.0/servicemonitor.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.22.2/prometheus.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.22.2/prometheusrule.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/0.22.2/servicemonitor.crd.yaml
  pkg/sqlite/testdata/loader_data/prometheus/prometheus.package.yaml
Labels: approved, lgtm

#229 [feature] Understanding packages from directory
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  go.sum
  pkg/lib/bundle/build.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/interpreter.go
  pkg/lib/bundle/interpreter_test.go
  pkg/registry/csv.go
  pkg/registry/csv_test.go
  pkg/registry/directoryGraphLoader.go
  pkg/registry/directoryGraphLoader_test.go
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apimanagers.apps.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apis.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/bindings.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/limits.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/mappingrules.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/metrics.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/plans.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/tenants.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/3scale-community-operator.package.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/etcd.package.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/prometheus.package.yaml
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/modules.txt
Labels: approved, lgtm

#239 Revert "[feature] Understanding packages from directory"
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
  go.sum
  pkg/lib/bundle/build.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/interpreter.go
  pkg/lib/bundle/interpreter_test.go
  pkg/registry/csv.go
  pkg/registry/csv_test.go
  pkg/registry/directoryGraphLoader.go
  pkg/registry/directoryGraphLoader_test.go
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apimanagers.apps.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/apis.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/bindings.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/limits.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/mappingrules.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/metrics.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/plans.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.3.0/tenants.capabilities.3scale.net.crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/3scale-community-operator.package.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdbackup.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdcluster.crd.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdrestore.crd.yaml
  pkg/registry/testdata/validPackages/etcd/etcd.package.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.14.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.15.0/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheus.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/prometheusrule.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/0.22.2/servicemonitor.crd.yaml
  pkg/registry/testdata/validPackages/prometheus/prometheus.package.yaml
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/modules.txt
Labels: approved, lgtm

#234 Fixing ci and travis tests
  .travis.yml
  Dockerfile
Labels: approved, lgtm

#237 pkg/lib/bundle: fix copyManifestDir so it actually copies file contents
  pkg/lib/bundle/generate.go
Labels: approved, kind/bug, lgtm

#227 fix(dns): fix slow dns resolution of localhost for grpc health probe
  cmd/appregistry-server/main.go
  cmd/configmap-server/main.go
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/lib/dns/nsswitch.go
  pkg/lib/dns/nsswitch_test.go
Labels: approved, lgtm
