Repository operator-framework/operator-registry, pull requests merged in 2020-11, with the labels that each got.

#506 Bug 1894278: (fix) close connection to db
  pkg/sqlite/query.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#508 Fix Go version used by release job to 1.14.z.
  .github/workflows/release.yaml
Labels: approved, lgtm

#505 Bug 1889721: add skippatch unit test
  pkg/registry/bundlegraphloader_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#512 Bug 1889388: Reconstruct replaces and skips for ListBundles from channel_entry.
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#432 Add ConsoleYamlSamples to the supported resources
  pkg/lib/bundle/supported_resources.go
Labels: approved, lgtm, ok-to-test

#480 fix the description of validation "RegistryV1" format
  docs/design/operator-bundle.md
Labels: approved, kind/documentation, lgtm, ok-to-test

#503 Bug 1885425: fix(indexing): order bulk add by version field
  bundles/prometheus.0.14.0-beta/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  cmd/opm/index/add.go
  go.mod
  pkg/containertools/containertoolsfakes/fake_command_runner.go
  pkg/lib/bundle/validate.go
  pkg/lib/indexer/indexerfakes/fake_index_exporter.go
  pkg/lib/validation/bundle_test.go
  pkg/registry/bundle.go
  pkg/registry/bundle_test.go
  pkg/registry/decode.go
  pkg/registry/empty.go
  pkg/registry/imageinput.go
  pkg/registry/input_stream.go
  pkg/registry/input_stream_test.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/registry/registryfakes/fake_graph_loader.go
  pkg/registry/replacesgraphloader.go
  pkg/sqlite/configmap.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/query.go
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#509 copy .git directory for build tag info
  Dockerfile
  appr-registry.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm

#499 Bug 1892395: [release-4.6] TestListPackages is flaky
  pkg/server/server_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#523 fix(indexing): respect strict mode
  pkg/registry/input_stream.go
  pkg/registry/input_stream_test.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
Labels: approved, lgtm

#520 Bug 1892360: Reconstruct replaces/splits for Listbundles from channel_entry.
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#495 feat: add opm support for optional validators and custom category validation
  cmd/opm/alpha/bundle/validate.go
  go.mod
  go.sum
  pkg/lib/bundle/interfaces.go
  pkg/lib/bundle/validate.go
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/pkg/manifests/bundle.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundleloader.go
  vendor/github.com/operator-framework/api/pkg/operators/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/register.go
  vendor/github.com/operator-framework/api/pkg/operators/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/bundle.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/object.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/typecheck.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
Labels: approved, lgtm
