Repository operator-framework/operator-registry, pull requests merged in 2020-05, with the labels that each got.

#314 Bug 1829994: Index generate dameonless
  cmd/opm/index/add.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/interfaces.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#306 Bug 1827738: feat(opm): add version command
  cmd/opm/main.go
  cmd/opm/version/version.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#324 Bug 1827723: Adding error message for more than one CSV in bundle dir
  go.mod
  go.sum
  pkg/registry/csv.go
  pkg/registry/csv_test.go
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/3scale-community-operator.v0.4.0.clusterserviceversion.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/apps_v1alpha1_apimanager_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_api_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_binding_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_limit_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_mappingrule_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_metric_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_plan_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/capabilities_v1alpha1_tenant_crd.yaml
  pkg/registry/testdata/invalidPackges/3scale-community-operator/0.4.0/duplicate.csv.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#321 Bug 1827738: add build flags to opm to show version information
  Makefile
  OPM_VERSION
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#276 [release-4.4] Bug 1816184: fix(dns): fix slow dns resolution of localhost for grpc health probe #269
  Dockerfile
  cmd/appregistry-server/main.go
  cmd/configmap-server/main.go
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/lib/dns/nsswitch.go
  pkg/lib/dns/nsswitch_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#320 Bug 1835887: upstream-opm-builder.Dockerfile: add ca-certificates
  upstream-opm-builder.Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#334 Bug 1838756: fix(validation): Fix CRD v1beta int-float conversion error
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdclusters.etcd.database.coreos.com.crd.yaml
  pkg/lib/bundle/validate.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#332 Bug 1827612: fix(server): make a copy of the db before migrating it
  Dockerfile
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/lib/tmp/copy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#338 Bug 1835884: opm bundle extract shouldn't validate annotations
  pkg/configmap/configmap_test.go
  pkg/configmap/configmap_writer.go
  pkg/configmap/testdata/bundle-with-no-default-channel.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#337 Bug 1840370: Configure "podman build" to produce images with Docker manifests.
  pkg/appregistry/dbloader.go
  pkg/containertools/containertool.go
  pkg/containertools/factory.go
  pkg/containertools/factory_docker.go
  pkg/containertools/factory_podman.go
  pkg/containertools/factory_stub.go
  pkg/containertools/factory_test.go
  pkg/containertools/option_build.go
  pkg/containertools/runner.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#340 Bug 1840727: fix(unpack): support unpacking readonly folders
  pkg/image/containerdregistry/registry.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#341 docs: add OPM_VERSION notes to release docs
  docs/contributors/releases.md
Labels: approved, lgtm
