Repository operator-framework/operator-registry, pull requests merged in 2020-10, with the labels that each got.

#466 Bug 1882103: set group permissions on /etc
  upstream-builder.Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#469 OWNERS: add operator-sdk reviewers estroz, joelanford, jmrodri
  OWNERS
Labels: approved, lgtm

#454 fix the comments of LabelDependency in the type definition
  pkg/registry/types.go
Labels: approved, lgtm, ok-to-test

#425 Add USER for non-root image usage
  configmap-registry.Dockerfile
Labels: approved, lgtm, ok-to-test

#290 update the help info of the export subcommand
  cmd/opm/index/export.go
Labels: approved, lgtm, ok-to-test

#461 Bug 1883560: fix(dockerfile): clean out tmp directory after binaries are placed
  Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#464 Bug 1883905: (fix) concurrent writes during image pulls
  pkg/lib/registry/registry.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#474 Make the inability to create /etc/nsswitch.conf non-fatal.
  appr-registry.Dockerfile
  cmd/appregistry-server/main.go
  cmd/configmap-server/main.go
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  configmap-registry.Dockerfile
  index.Dockerfile
  nsswitch.conf
  opm-example.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-example.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm

#477 Fix test flake based on random aggregate error order.
  pkg/registry/populator_test.go
Labels: approved, lgtm

#475 Add writable workdir to configmap registry image.
  configmap-registry.Dockerfile
Labels: approved, lgtm

#481 Bug 1883773: Fix path separator in generated bundle Dockerfiles on Windows.
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#485 Bug 1881527: fix(opm): properly deprecate export flag '-o'
  cmd/opm/index/export.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#486 Bug 1889721: Check prerelease version for semver-skippatch mode
  pkg/registry/bundlegraphloader.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#491 Start listening on test server port before running tests.
  pkg/server/server_test.go
Labels: approved, lgtm

#483 Bug 1889388: Set replaces in ListBundles query result using channel entries.
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#490 Add coverage report job.
  .github/workflows/unit.yaml
  .gitignore
  Makefile
Labels: approved, lgtm

#493 Remove unused file.
  pkg/sqlite/test.txt
Labels: approved, lgtm

#494 Completely populate test database before executing tests.
  pkg/server/server_test.go
Labels: approved, lgtm

#496 Add Github Actions release workflow.
  .github/workflows/release.yaml
  .travis.yml
Labels: approved, lgtm

#500 Produce opm linux release binaries for ppc64le and s390x.
  .github/workflows/release.yaml
Labels: approved, lgtm

#501 Build upstream releases with Go 1.14 instead of 1.15.
  .github/workflows/release.yaml
Labels: approved, lgtm
