Repository operator-framework/operator-registry, pull requests merged in 2020-02, with the labels that each got.

#167 Delete junk SQLite journal files.
  pkg/sqlite/migrations/1048603298946505393.db-journal
  pkg/sqlite/migrations/1605093295757842313.db-journal
  pkg/sqlite/migrations/1723623752989124754.db-journal
  pkg/sqlite/migrations/2185498746914453466.db-journal
  pkg/sqlite/migrations/227796661730793138.db-journal
  pkg/sqlite/migrations/3663046655478159228.db-journal
  pkg/sqlite/migrations/4356584978060083866.db-journal
  pkg/sqlite/migrations/5830462186904655686.db-journal
  pkg/sqlite/migrations/5833681874785676064.db-journal
  pkg/sqlite/migrations/7316970654267064916.db-journal
  pkg/sqlite/migrations/8458472522999605221.db-journal
Labels: approved, lgtm, size/XS

#172 Update operator-bundle to clarify the bundle format directories
  docs/design/operator-bundle.md
Labels: approved, lgtm, size/M

#173 fix(index): copy correct opm bin builder path
  index.Dockerfile
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
Labels: approved, lgtm, size/XS

#183 Bug 1800460: fix(docker): add entrypoint
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#189 Produce binaries without target platform prefixes by default.
  .travis.yml
  Dockerfile
  Makefile
  appr-registry.Dockerfile
  configmap-registry.Dockerfile
  opm-example.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
Labels: approved, lgtm, size/M

#195 test(meta-pruning): ensure pathless nodes keep data
  pkg/sqlite/load_test.go
Labels: approved, lgtm, size/M

#194 Add stale bot
  .github/stale.yml
Labels: approved, lgtm, size/S

#197 fix(index): gen index dockerfiles from opm image
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
Labels: approved, lgtm, size/M

#198 Removing olm dependency
  go.mod
  go.sum
  pkg/lib/bundle/validate.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/hashicorp/golang-lru/go.mod
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/operator-framework/api/pkg/lib/version/version.go
  vendor/github.com/operator-framework/api/pkg/operators/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/register.go
  vendor/github.com/operator-framework/api/pkg/operators/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.conversion.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/bundle.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/LICENSE
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
