Repository operator-framework/operator-registry, pull requests merged in 2021-04, with the labels that each got.

#622 go.sum: Re-sync vendor dependencies
  go.sum
Labels: approved, lgtm

#623 .github: Separate the jobs in the test workflow into their own workflows
  .github/workflows/build.yaml
  .github/workflows/sanity.yaml
  .github/workflows/test.yml
  .github/workflows/unit.yaml
Labels: approved, lgtm

#624 bump api version to v0.7.1
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/pkg/operators/v1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operator_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/annotations.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorgroup.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/typecheck.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
Labels: approved, lgtm, ok-to-test

#601 Implement registry server for declarative config
  cmd/opm/root/cmd.go
  cmd/opm/serve/serve.go
  pkg/api/api_to_model.go
  pkg/api/model_to_api.go
  pkg/registry/interface.go
  pkg/registry/query.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/sqlite/conversion.go
Labels: approved, feat/declarative-config, lgtm

#582 feat(declarative-config): opm add creates declarative configs
  Makefile
  cmd/opm/root/add.go
  cmd/opm/root/cmd.go
  internal/model/model.go
  internal/model/model_test.go
  pkg/action/add_bundle_to_configs.go
  pkg/action/bundle_extractor.go
  pkg/registry/bundle.go
  pkg/registry/csv.go
  pkg/registry/registry_to_model.go
  pkg/registry/registry_to_model_test.go
  test/e2e/opm_configs_test.go
  test/e2e/testdata/test-configs/prometheus/prometheus.json
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, feat/declarative-config, lgtm

#626 Delete the symbolically linked operator-registry.Dockerfile
  operator-registry.Dockerfile
Labels: approved, lgtm

#618 feat(cmd): Add validate subcommand to opm cmd to validate config files
  cmd/opm/root/cmd.go
  cmd/opm/validate/validate.go
  internal/declcfg/declcfg_to_model.go
  internal/declcfg/declcfg_to_model_test.go
  internal/declcfg/helpers_test.go
  internal/model/model.go
  internal/model/model_test.go
  pkg/lib/config/validate.go
Labels: approved, feat/declarative-config, lgtm

#628 (opm) move add from root to alpha
  cmd/opm/alpha/add/cmd.go
  cmd/opm/alpha/cmd.go
  cmd/opm/root/cmd.go
Labels: approved, lgtm

#612 (feat) substitutes-for logic
  bundles/prometheus.0.14.0.substitutesfor/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor/manifests/prometheus.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  bundles/prometheus.0.14.0.substitutesfor/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor/metadata/annotations.yaml
  bundles/prometheus.0.14.0.substitutesfor2/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor2/manifests/prometheus.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor2/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  bundles/prometheus.0.14.0.substitutesfor2/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor2/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor2/metadata/annotations.yaml
  bundles/prometheus.0.14.0.substitutesfor3/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor3/manifests/prometheus.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor3/manifests/prometheusoperator.0.14.0.clusterserviceversion.yaml
  bundles/prometheus.0.14.0.substitutesfor3/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor3/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.14.0.substitutesfor3/metadata/annotations.yaml
  bundles/prometheus.0.15.0.substitutesfor/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor/manifests/prometheus.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  bundles/prometheus.0.15.0.substitutesfor/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor/metadata/annotations.yaml
  bundles/prometheus.0.15.0.substitutesfor2/manifests/alertmanager.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor2/manifests/prometheus.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor2/manifests/prometheusoperator.0.15.0.clusterserviceversion.yaml
  bundles/prometheus.0.15.0.substitutesfor2/manifests/prometheusrule.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor2/manifests/servicemonitor.crd.yaml
  bundles/prometheus.0.15.0.substitutesfor2/metadata/annotations.yaml
  cmd/opm/index/add.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  pkg/lib/semver/semver.go
  pkg/lib/semver/semver_test.go
  pkg/registry/bundle.go
  pkg/registry/csv.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/sqlite/db_options.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/011_substitutes_for_test.go
  pkg/sqlite/migrations/011_susbtitutes_for.go
Labels: approved, lgtm

#621 Accept any property type in olm.properties annotation
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/server/server_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
Labels: approved, lgtm

#635 .github/workflows: Fix the podman installation in the e2e tests
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: approved, lgtm

#639 Replace codecov-action with vendored upload script.
  .github/workflows/codecov.sh
  .github/workflows/unit.yaml
Labels: approved, lgtm

#633 Retry failures when pulling images
  go.mod
  pkg/action/bundle_extractor.go
  pkg/image/buildahregistry/_registry.go
  pkg/image/containerdregistry/registry.go
  pkg/image/registry_test.go
  pkg/lib/image/registry.go
  vendor/modules.txt
Labels: approved, lgtm

#642 Bug 1951387: (bug) add after deprecation
  pkg/registry/populator_test.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#645 Force latest install of podman to fix currently broken e2e tests
  .github/workflows/test.yml
Labels: approved, lgtm

#595 Add optional go-apidiff test to CI
  .github/workflows/go-apidiff.yaml
Labels: approved, lgtm

#643 [release-4.7] Bug 1937097: Add retries to opm index add
  .github/workflows/test.yml
  go.mod
  pkg/image/buildahregistry/_registry.go
  pkg/image/containerdregistry/registry.go
  pkg/image/registry_test.go
  pkg/lib/image/registry.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#646 Move config serve and validate to opm alpha
  cmd/opm/alpha/cmd.go
  cmd/opm/alpha/serve/serve.go
  cmd/opm/alpha/validate/validate.go
  cmd/opm/root/cmd.go
Labels: approved, lgtm
