Repository operator-framework/operator-registry, pull requests merged in 2021-01, with the labels that each got.

#541 Bug 1909464: Fix windows build with golang 1.15
  Dockerfile
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#548 Bug 1915408: load required docker images for kind cluster in e2e test
  test/e2e/bundle_image_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#532 Bug 1904547: Include the bundle image itself as a related image.
  pkg/registry/bundle.go
  pkg/registry/bundle_test.go
  pkg/registry/populator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#556 Bug 1904297: Unexpected images left in `related_images` after pruning
  cmd/configmap-server/main.go
  cmd/initializer/main.go
  cmd/opm/registry/serve.go
  cmd/registry-server/main.go
  pkg/appregistry/builder.go
  pkg/appregistry/dbloader.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/indexer_test.go
  pkg/lib/registry/registry.go
  pkg/mirror/mirror.go
  pkg/mirror/mirror_test.go
  pkg/registry/interface.go
  pkg/registry/populator_test.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/db.go
  pkg/sqlite/load.go
  pkg/sqlite/migrations/001_related_images_test.go
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
  pkg/sqlite/remove.go
  pkg/sqlite/remove_test.go
  pkg/sqlite/stranded.go
  pkg/sqlite/stranded_test.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#552 Bug 1920205: use secure local registry for e2e tests
  .github/workflows/test.yml
  pkg/image/containerdregistry/resolver.go
  test/e2e/e2e_suite_test.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#535 Bug 1889865: Avoid duplicate registry binaries across downstream image layers.
  Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
