Repository operator-framework/operator-registry, pull requests merged in 2021-08, with the labels that each got.

#610 Fix nil function in buildContext return values
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/indexer_test.go
Labels: approved, lgtm, ok-to-test

#733 internal/declcfg: Avoid processing the .indexignore file when walking the root fs
  internal/declcfg/load.go
Labels: approved, lgtm

#710 opm: add multi-arch builds with goreleaser
  .github/workflows/goreleaser.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
  release/goreleaser.opm.Dockerfile
  scripts/fetch
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm, tide/merge-method-merge

#735 docs(diff): add point about versions that differ
  cmd/opm/alpha/diff/cmd.go
Labels: approved, kind/documentation, lgtm

#730 .github/workflows: Replace the e2e-kind job name with e2e in the test workflow
  .github/workflows/test.yml
Labels: approved, lgtm

#744 Handle property and dependency values of type BLOB in ListBundles.
  pkg/sqlite/query.go
  pkg/sqlite/query_sql_test.go
Labels: approved, lgtm

#732 check for pruned bundles on add in replaces mode
  cmd/opm/index/add.go
  pkg/lib/registry/registry.go
  pkg/lib/registry/registry_test.go
Labels: approved, lgtm

#740 chore(opm): note that whole dependency packages are added to the diff
  cmd/opm/alpha/diff/cmd.go
Labels: approved, lgtm

#746 fix(deprecate): explicit pkg rm drops latest deprecated
  pkg/lib/registry/registry.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/migrations/013_rm_truncated_deprecations.go
  pkg/sqlite/migrations/013_rm_truncated_deprecations_test.go
Labels: approved, lgtm

#734 feat: support removing the default channel head in deprecatetruncate
  cmd/opm/index/deprecatetruncate.go
  pkg/lib/indexer/indexer.go
  pkg/lib/registry/registry.go
  pkg/registry/populator_test.go
  pkg/sqlite/deprecate.go
  pkg/sqlite/query.go
  test/e2e/opm_test.go
Labels: approved, lgtm

#741 fix(opm): clarify that bundle declcfgs are not valid refs alone
  cmd/opm/alpha/diff/cmd.go
  internal/action/diff.go
  internal/action/diff_test.go
  internal/action/list.go
  internal/action/render.go
  internal/action/render_test.go
Labels: approved, lgtm

#738 feat(release): X.Y, X, and latest opm image tags
  .goreleaser.yaml
  Makefile
Labels: approved, lgtm

#750 cli doc: opm serve does not detect DC changes after startup
  cmd/opm/serve/serve.go
Labels: approved, lgtm

#751 Add joelanford as an approver in OWNERS
  OWNERS
Labels: approved, lgtm

#758 Fix upstream-opm-builder build error due to rate limiting
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm

#753 feat(opm): configure diff to not include dependency bundles with --skip-deps
  cmd/opm/alpha/diff/cmd.go
  internal/action/diff.go
  internal/declcfg/diff.go
  internal/declcfg/diff_test.go
Labels: kind/feature, approved, lgtm

#755 opm validate: check for cycles and stranded bundles in channel validation
  alpha/model/model.go
  alpha/model/model_test.go
Labels: approved, lgtm

#743 add further console customization types
  pkg/lib/bundle/supported_resources.go
Labels: approved, lgtm

#762 update default scaffolded opm base image
  opm-example.Dockerfile
  pkg/containertools/dockerfilegenerator.go
  pkg/containertools/dockerfilegenerator_test.go
Labels: approved, lgtm
