Repository operator-framework/operator-registry, pull requests merged in 2021-03, with the labels that each got.

#587 Deprecate initializer and registry-server
  README.md
Labels: approved, lgtm, ok-to-test

#604 Bump all Go binary builds to 1.15
  .github/workflows/release.yaml
  .github/workflows/test.yml
  appr-registry.Dockerfile
  codegen.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm

#598 test/e2e: Fix output log message when Podman is not found
  test/e2e/opm_test.go
Labels: approved, lgtm

#607 Bump to Go 1.16
  .github/workflows/release.yaml
  appr-registry.Dockerfile
  codegen.Dockerfile
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm

#596 .github: Add a sanity check for Go packages
  .github/workflows/test.yml
  Makefile
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/grpc_health_v1/health_grpc.pb.go
  pkg/api/registry.pb.go
  pkg/api/registry_grpc.pb.go
  pkg/image/containerdregistry/resolver.go
  pkg/image/registry.go
  pkg/lib/bundle/interfaces.go
  pkg/lib/dns/nsswitch_test.go
  pkg/lib/indexer/indexer_test.go
  pkg/registry/bundlegraphloader_test.go
  pkg/registry/csv_test.go
  pkg/registry/decode_test.go
  pkg/server/server.go
  pkg/sqlite/db.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle_test.go
  pkg/sqlite/remove_test.go
  tools.go
Labels: approved, lgtm

#613 test/e2e: Disable the bundle unpack opm e2e tests
  test/e2e/opm_bundle_test.go
Labels: approved, lgtm

#614 Dockerfile: Add a symbolically linked release Dockerfile
  operator-registry.Dockerfile
Labels: approved, lgtm

#611 `opm registry add`: add `--ca-file` to add a cert to the pool used by the command
  cmd/opm/registry/add.go
  docs/design/opm-tooling.md
Labels: approved, kind/feature, lgtm
