Repository operator-framework/operator-registry, pull requests merged in 2021-06, with the labels that each got.

#669 fix(sqlite): upsert deprecation table entries
  pkg/sqlite/load.go
  pkg/sqlite/migrations/012_deprecated.go
  pkg/sqlite/migrations/012_deprecated_test.go
Labels: approved, lgtm

#670 Add draft release info to opm release doc
  docs/contributors/releases.md
Labels: approved, lgtm

#661 Add opm alpha init/render commands.
  cmd/opm/alpha/cmd.go
  cmd/opm/alpha/init/cmd.go
  cmd/opm/alpha/render/cmd.go
  internal/action/init.go
  internal/action/init_test.go
  internal/action/render.go
  internal/action/render_test.go
  internal/action/testdata/foo-bundle-v0.1.0/bundle.Dockerfile
  internal/action/testdata/foo-bundle-v0.1.0/manifests/foo.v0.1.0.csv.yaml
  internal/action/testdata/foo-bundle-v0.1.0/manifests/foos.test.foo.crd.yaml
  internal/action/testdata/foo-bundle-v0.1.0/metadata/annotations.yaml
  internal/action/testdata/foo-bundle-v0.1.0/metadata/dependencies.yaml
  internal/action/testdata/foo-bundle-v0.2.0/bundle.Dockerfile
  internal/action/testdata/foo-bundle-v0.2.0/manifests/foo.v0.2.0.csv.yaml
  internal/action/testdata/foo-bundle-v0.2.0/manifests/foos.test.foo.crd.yaml
  internal/action/testdata/foo-bundle-v0.2.0/metadata/annotations.yaml
  internal/action/testdata/foo-bundle-v0.2.0/metadata/dependencies.yaml
  internal/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  internal/action/testdata/foo-index-v0.2.0-sqlite/database/index.db
  internal/declcfg/load.go
  internal/declcfg/load_test.go
  internal/declcfg/testdata/valid/etcd.yaml
  internal/model/model_test.go
  internal/property/property.go
  pkg/api/api_to_model.go
  pkg/api/conversion_test.go
  pkg/image/mock.go
  pkg/image/mock_test.go
  pkg/registry/registry_to_model.go
  pkg/server/server_test.go
  pkg/sqlite/conversion.go
Labels: approved, lgtm

#674 Remove `opm alpha add`, `declcfg.WriteDir`, and related now-unused code/tests
  cmd/opm/alpha/add/cmd.go
  cmd/opm/alpha/cmd.go
  internal/declcfg/load_test.go
  internal/declcfg/testdata/valid/etcd.yaml
  internal/declcfg/testdata/valid/etcdoperator.v0.6.1.clusterserviceversion.yaml
  internal/declcfg/write.go
  internal/declcfg/write_test.go
  pkg/action/add_bundle_to_configs.go
  pkg/action/bundle_extractor.go
  test/e2e/opm_configs_test.go
Labels: approved, lgtm

#668 fix example bundle dockerfile so that it copies the manifests folder
  docs/design/operator-bundle.md
Labels: approved, lgtm, ok-to-test

#671 Explicit bundle properties
  internal/property/property.go
  pkg/registry/bundle.go
  pkg/registry/csv.go
  pkg/registry/decode.go
  pkg/registry/decode_test.go
  pkg/registry/imageinput.go
  pkg/registry/parse.go
  pkg/registry/parse_test.go
  pkg/registry/populator.go
  pkg/registry/registry_to_model_test.go
  pkg/registry/types.go
Labels: approved, lgtm

#627 Remove travis build badge from README.md
  README.md
Labels: approved, lgtm

#680 declcfg: change LoadDir to LoadFS
  cmd/opm/alpha/serve/serve.go
  internal/action/render.go
  internal/declcfg/load.go
  internal/declcfg/load_test.go
  internal/declcfg/testdata/invalid/invalid-bundle-json.json
  internal/declcfg/testdata/invalid/invalid-package-json.json
  internal/declcfg/testdata/invalid/no-schema.yaml
  internal/declcfg/testdata/invalid/not-yaml-or-json-object.json
  internal/declcfg/testdata/invalid/not-yaml-or-json.txt
  internal/declcfg/testdata/valid/.indexignore
  internal/declcfg/testdata/valid/README.md
  internal/declcfg/testdata/valid/cockroachdb.json
  internal/declcfg/testdata/valid/etcd.yaml
  internal/declcfg/testdata/valid/etcdoperator.v0.6.1.clusterserviceversion.yaml
  internal/declcfg/testdata/valid/unrecognized-schema.json
  internal/property/property.go
  internal/property/property_test.go
  pkg/lib/config/validate.go
  pkg/registry/query_test.go
  pkg/registry/testdata/validDeclCfg/cockroachdb.json
  pkg/registry/testdata/validDeclCfg/etcd.json
Labels: approved, lgtm

#656 check presence of all bundles before deprecate
  pkg/lib/registry/registry.go
  pkg/lib/registry/registry_test.go
Labels: approved, lgtm

#688 allow out of order deprecate
  pkg/registry/populator_test.go
  pkg/sqlite/deprecate.go
Labels: approved, lgtm

#678 [release-4.6] Bug 1968681: fix(containerd): drop xattrs during unpack
  pkg/image/containerdregistry/registry.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#691 declcfg: validation should allow non-existent replaces value
  internal/model/model.go
Labels: approved, lgtm

#684 Declarative Config: output validation errors as tree
  cmd/opm/alpha/validate/validate.go
  go.mod
  go.sum
  internal/model/error.go
  internal/model/error_test.go
  internal/model/model.go
  pkg/lib/config/validate.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: approved, lgtm
