Repository operator-framework/operator-registry, pull requests merged in 2021-02, with the labels that each got.

#572 fix: use none driver without sudo in upstream minikube e2e tests
  .github/workflows/test.yml
Labels: approved, lgtm

#571 Bug 1921778: Add build metadata version precedence
  pkg/lib/indexer/indexer.go
  pkg/registry/graph.go
  pkg/registry/helper_test.go
  pkg/registry/input_stream.go
  pkg/registry/input_stream_test.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/opm_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#559 Add doc on opm v1.15.3 index add behavior
  docs/design/opm-tooling.md
Labels: kind/documentation

#558 Fix upstream example dockerfile
  upstream-example.Dockerfile
Labels: approved, lgtm

#580 Fix typo in deprecate+truncate command help
  cmd/opm/index/deprecatetruncate.go
Labels: approved, lgtm

#547 [release-4.6] Bug 1915068: Fix windows build with golang 1.15
  Dockerfile
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test

#546 docs/design: Minor documentation fixes
  docs/design/operator-bundle.md
  docs/design/opm-tooling.md
Labels: approved, lgtm

#570 Bug 1921763: add missing closes
  pkg/registry/csv.go
  pkg/sqlite/directory.go
  pkg/sqlite/load.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#585 fix: add apt-get-upgrade to ci script, skip podman tests
  .github/workflows/test.yml
  test/e2e/opm_test.go
Labels: approved

#564 doc: clarifies opm usage and what tool can help with bundles
  README.md
Labels: approved, lgtm

#557 Add details for starting a local server to README
  README.md
Labels: approved, lgtm

#565 upgrade to use go 1.15
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#418 feat(opm): add alpha bundle unpack command
  cmd/opm/alpha/bundle/cmd.go
  cmd/opm/alpha/bundle/unpack.go
  cmd/opm/main.go
  cmd/opm/root/cmd.go
  pkg/image/containerdregistry/registry.go
  pkg/lib/bundle/validate.go
  pkg/lib/image/registry.go
  test/e2e/e2e_suite_test.go
  test/e2e/opm_bundle_test.go
Labels: approved, lgtm

#588 .github,test: Re-enable Podman e2e tests
  .github/workflows/test.yml
  test/e2e/opm_test.go
Labels: approved, lgtm

#593 OWNERS: Update the owner file
  OWNERS
Labels: approved, lgtm

#591 cmd,pkg: Deflate unnecessary conditionals
  cmd/opm/index/add.go
  pkg/lib/bundle/utils_test.go
  pkg/lib/registry/registry.go
  pkg/lib/validation/bundle.go
  pkg/registry/bundlegraphloader.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#590 Update the vendor Makefile target and update the vendored dependencies
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/modules.txt
Labels: approved, lgtm

#594 README: Address markdown violations
  README.md
Labels: approved, lgtm
