Repository operator-framework/operator-registry, pull requests merged in 2021-09, with the labels that each got.

#769 Mark GetBundleForChannel as deprecated and trim its response.
  pkg/api/registry.proto
  pkg/registry/interface.go
  pkg/registry/populator_test.go
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#771 fix: ensure operator images are included in rendered bundles related images
  alpha/action/render.go
  alpha/action/render_test.go
  alpha/action/testdata/foo-bundle-v0.2.0/manifests/foo.v0.2.0.csv.yaml
  alpha/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
Labels: approved, lgtm

#768 Introduce olm.channel schema, remove channel metadata-related bundle properties
  alpha/action/list.go
  alpha/action/render.go
  alpha/action/render_test.go
  alpha/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
  alpha/action/testdata/index-declcfgs/exp-headsonly/index.yaml
  alpha/action/testdata/index-declcfgs/exp-latest/index.yaml
  alpha/action/testdata/index-declcfgs/latest/index.yaml
  alpha/action/testdata/index-declcfgs/old/index.yaml
  alpha/action/testdata/list-index/bar/index.yaml
  alpha/action/testdata/list-index/foo/index.yaml
  alpha/declcfg/declcfg.go
  alpha/declcfg/declcfg_to_model.go
  alpha/declcfg/declcfg_to_model_test.go
  alpha/declcfg/diff_test.go
  alpha/declcfg/helpers_test.go
  alpha/declcfg/load.go
  alpha/declcfg/model_to_declcfg.go
  alpha/declcfg/model_to_declcfg_test.go
  alpha/declcfg/properties.go
  alpha/declcfg/properties_test.go
  alpha/declcfg/write.go
  alpha/declcfg/write_test.go
  alpha/model/model.go
  alpha/model/model_test.go
  alpha/property/property.go
  alpha/property/property_test.go
  alpha/property/scheme.go
  pkg/api/api_to_model.go
  pkg/api/conversion_test.go
  pkg/api/model_to_api.go
  pkg/registry/query_test.go
  pkg/registry/registry_to_model.go
  pkg/registry/registry_to_model_test.go
  pkg/server/server_test.go
  pkg/sqlite/conversion.go
Labels: approved, lgtm

#773 fix(release): upgrade goreleaser so script requests correct checksum file
  Makefile
Labels: approved, lgtm

#756 feat(opm): fine-grained dependency selection in diffs
  alpha/action/testdata/index-declcfgs/exp-headsonly/index.yaml
  alpha/action/testdata/index-declcfgs/latest/index.yaml
  alpha/action/testdata/index-declcfgs/old/index.yaml
  alpha/declcfg/diff.go
  alpha/declcfg/diff_include.go
  alpha/declcfg/diff_include_test.go
  alpha/declcfg/diff_test.go
Labels: approved, lgtm

#778 opm: build fully static opm binaries/images
  .goreleaser.yaml
  release/goreleaser.opm.Dockerfile
Labels: approved, lgtm

#716 feat(opm diff): include packages, channels, and versions in diff output
  alpha/action/diff.go
  alpha/action/diff_test.go
  alpha/declcfg/diff.go
  alpha/declcfg/diff_include.go
  cmd/opm/alpha/diff/cmd.go
Labels: kind/feature, approved, lgtm

#783 opm serve: pre-compute and store api.Bundles to disk; requests read from disk
  Makefile
  cmd/opm/serve/serve.go
  pkg/lib/registry/registry_test.go
  pkg/registry/parse.go
  pkg/registry/query.go
  pkg/registry/query_test.go
  pkg/server/server_test.go
Labels: approved, lgtm

#694 Update case to match resource.
  pkg/lib/bundle/supported_resources.go
Labels: approved, lgtm, ok-to-test

#780 fix: Unable to deprecate bundles that are head of a NOT default channel with opm deprecatetruncate
  bundles/apicurio-registry-operator.v1.0.0-v2.0.0.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
  bundles/apicurio-registry.v0.0.1/manifests/apicurio-registry-operator.v0.0.1.clusterserviceversion.yaml
  bundles/apicurio-registry.v0.0.3-v1.2.3.final/manifests/apicurio-registry.v0.0.3-v1.2.3.final.clusterserviceversion.yaml
  bundles/apicurio-registry.v0.0.4-v1.3.2.final/manifests/apicurio-registry.v0.0.4-v1.3.2.final.clusterserviceversion.yaml
  pkg/registry/populator_test.go
  pkg/sqlite/load.go
  pkg/sqlite/query.go
Labels: approved, lgtm

#789 Update long description indentation for alpha
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/generate.go
Labels: approved, lgtm

#786 Update opm commands to specifcy if they don't take args
  cmd/opm/alpha/bundle/build.go
  cmd/opm/alpha/bundle/cmd.go
  cmd/opm/alpha/bundle/extract.go
  cmd/opm/alpha/bundle/generate.go
  cmd/opm/alpha/bundle/validate.go
  cmd/opm/alpha/cmd.go
  cmd/opm/index/add.go
  cmd/opm/index/cmd.go
  cmd/opm/index/delete.go
  cmd/opm/index/deprecatetruncate.go
  cmd/opm/index/export.go
  cmd/opm/index/prune.go
  cmd/opm/index/prunestranded.go
  cmd/opm/registry/add.go
  cmd/opm/registry/cmd.go
  cmd/opm/registry/mirror.go
  cmd/opm/registry/prune.go
  cmd/opm/registry/prunestranded.go
  cmd/opm/registry/rm.go
  cmd/opm/registry/serve.go
  cmd/opm/root/cmd.go
Labels: approved, lgtm

#767 handle deprecating branch points
  alpha/action/render_test.go
  pkg/lib/registry/registry.go
  pkg/lib/registry/registry_test.go
  pkg/registry/interface.go
  pkg/registry/populator.go
  pkg/registry/populator_test.go
  pkg/sqlite/load.go
  pkg/sqlite/load_test.go
  pkg/sqlite/migrations/013_rm_truncated_deprecations.go
  pkg/sqlite/remove_test.go
  pkg/sqlite/stranded_test.go
Labels: approved, lgtm

#770 migrate: add subcommand to migrate sqlite catalogs to file-based catalogs
  alpha/action/migrate.go
  alpha/action/migrate_test.go
  alpha/action/render.go
  alpha/action/render_test.go
  cmd/opm/migrate/cmd.go
  cmd/opm/root/cmd.go
Labels: approved, lgtm

#793 Enable cgo in multiarch builds
  .goreleaser.yaml
Labels: approved, lgtm, ok-to-test

#797 render: populate related images even when CSV has none explicitly defined
  alpha/action/render.go
  alpha/action/render_test.go
  alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/bundle.Dockerfile
  alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/manifests/foo.v0.2.0.csv.yaml
  alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/manifests/foos.test.foo.crd.yaml
  alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/metadata/annotations.yaml
  alpha/action/testdata/foo-bundle-v0.2.0-no-csv-related-images/metadata/dependencies.yaml
Labels: approved, lgtm

#796 Use the proper grpc_health_probe command per architectures.
  .github/workflows/goreleaser.yaml
  release/goreleaser.opm.Dockerfile
Labels: approved, lgtm, ok-to-test
