Repository operator-framework/operator-registry, pull requests merged in 2022-05, with the labels that each got.

#943 feat(opm): Add semver range support for olm alpha diff
  alpha/action/diff.go
  alpha/action/diff_test.go
  alpha/declcfg/diff_include.go
  alpha/declcfg/diff_test.go
Labels: approved, lgtm

#950 feat(diff): change HeadsOnly to be an explicit setting
  alpha/action/diff.go
  alpha/action/diff_test.go
  alpha/declcfg/diff.go
  alpha/declcfg/diff_include.go
  alpha/declcfg/diff_test.go
  cmd/opm/alpha/diff/cmd.go
Labels: approved, lgtm

#955 Update OWNERS to add 'grokspawn' as LGTMer.
  OWNERS
Labels: approved, lgtm

#958 fix(diff): adds empty channel pruning with an include config on lates…
  alpha/declcfg/diff.go
  alpha/declcfg/diff_test.go
Labels: approved, lgtm, ok-to-test

#954 :sparkles: improve message from common scenario faced to add a new bundle
  pkg/lib/registry/registry.go
  pkg/lib/registry/registry_test.go
Labels: approved, lgtm

#953 ✨ adds some extra text context to sql statement errors
  pkg/registry/populator.go
  pkg/sqlite/load.go
  pkg/sqlite/loadprocs.go
Labels: approved, lgtm

#946 Smooth phrasing in under-the-hood graph update passage
  docs/design/opm-tooling.md
Labels: lgtm
