Repository operator-framework/operator-registry, pull requests merged in 2022-09, with the labels that each got.

#1019 `opm alpha render-graph` support all valid action.render targets with channels
  cmd/opm/alpha/render-graph/cmd.go
Labels: approved, lgtm

#1020 OCPBUGS-929: fix help text for render-graph
  cmd/opm/alpha/render-graph/cmd.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1021 OCPBUGS-1004: (bug) semver veneer render: dump descriptive source info on error instead of the source data
  cmd/opm/alpha/veneer/semver.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1023 (feature) add skipRange support to `opm alpha render-graph` and provide the capability to filter mermaid output to a single package name
  alpha/declcfg/write.go
  alpha/declcfg/write_test.go
  cmd/opm/alpha/render-graph/cmd.go
  cmd/opm/alpha/veneer/semver.go
Labels: approved, lgtm

#1025 Updating workflows to pull go version from go.mod file
  .github/workflows/build.yaml
  .github/workflows/go-apidiff.yaml
  .github/workflows/goreleaser.yaml
  .github/workflows/sanity.yaml
  .github/workflows/test.yml
  .github/workflows/unit.yaml
Labels: approved, lgtm

#1026 OCPBUGS-1272 Add pipe support to "opm alpha render-veneer basic"
  alpha/declcfg/load.go
  alpha/declcfg/load_test.go
  alpha/veneer/basic/basic.go
  cmd/opm/alpha/veneer/basic.go
  cmd/opm/alpha/veneer/cmd.go
  cmd/opm/alpha/veneer/semver.go
Labels: approved, lgtm
