Repository operator-framework/operator-registry, pull requests merged in 2023-11, with the labels that each got.

#1157 Update api dependency to 0.19.0
  cmd/opm/alpha/bundle/validate.go
  go.mod
  go.sum
Labels: approved, lgtm

#1151 deprecation schema & import/render support
  alpha/action/render.go
  alpha/declcfg/declcfg.go
  alpha/declcfg/load.go
  alpha/declcfg/load_test.go
  alpha/declcfg/write.go
  alpha/template/semver/semver.go
Labels: approved, lgtm

#1161 grpc changes, model conversion, validation
  alpha/declcfg/declcfg.go
  alpha/declcfg/declcfg_to_model.go
  alpha/declcfg/load_test.go
  alpha/declcfg/write.go
  alpha/model/model.go
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/grpc_health_v1/health_grpc.pb.go
  pkg/api/model_to_api.go
  pkg/api/registry.pb.go
  pkg/api/registry.proto
  pkg/api/registry_grpc.pb.go
  pkg/cache/pkgs.go
  pkg/registry/conversion.go
  pkg/registry/types.go
Labels: approved, lgtm

#1166 chore: unnecessary use of fmt.Sprintf
  pkg/containertools/dockerfilegenerator.go
  pkg/lib/bundle/generate_test.go
Labels: needs-ok-to-test

#1167 chore: remove refs to deprecated io/ioutil
  alpha/action/init.go
  alpha/action/migrate.go
  alpha/action/render.go
  cmd/opm/alpha/bundle/unpack.go
  cmd/opm/alpha/bundle/validate.go
  cmd/opm/alpha/template/basic.go
  cmd/opm/alpha/template/semver.go
  cmd/opm/internal/util/util.go
  cmd/opm/render/cmd.go
  pkg/configmap/configmap_writer.go
  pkg/image/mock.go
  pkg/image/registry_test.go
  pkg/lib/bundle/chartutil.go
  pkg/lib/bundle/exporter.go
  pkg/lib/bundle/generate.go
  pkg/lib/bundle/generate_test.go
  pkg/lib/bundle/utils_test.go
  pkg/lib/bundle/validate.go
  pkg/lib/certs/certs.go
  pkg/lib/dns/nsswitch.go
  pkg/lib/dns/nsswitch_test.go
  pkg/lib/image/registry.go
  pkg/lib/indexer/indexer.go
  pkg/lib/indexer/indexer_test.go
  pkg/lib/log/writerhook.go
  pkg/lib/registry/registry.go
  pkg/lib/registry/registry_test.go
  pkg/lib/tmp/copy.go
  pkg/lib/validation/bundle_test.go
  pkg/registry/bundle_test.go
  pkg/registry/directoryGraphLoader.go
  pkg/registry/populator_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory.go
  test/e2e/bundle_image_test.go
  test/e2e/opm_bundle_test.go
  test/e2e/opm_test.go
Labels: approved, lgtm, ok-to-test

#1168 cleanup produced utest/dockerfile artifacts on test conclusion
  pkg/lib/indexer/indexer_test.go
Labels: approved, lgtm

#1165 containerdregistry: support per-repo credentials
  Makefile
  alpha/action/list_test.go
  cmd/configmap-server/main.go
  cmd/opm/registry/serve.go
  cmd/opm/serve/serve.go
  cmd/registry-server/main.go
  go.mod
  go.sum
  pkg/api/grpc_health_v1/health.pb.go
  pkg/api/grpc_health_v1/health.proto
  pkg/api/grpc_health_v1/health_grpc.pb.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/image/containerdregistry/options.go
  pkg/image/containerdregistry/registry.go
  pkg/image/containerdregistry/resolver.go
  pkg/server/health.go
Labels: approved
