Repository operator-framework/operator-registry, pull requests merged in 2023-03, with the labels that each got.

#1065 OPECO-2596: semver should generate replaces across Y-streams in minor-channel mode
  alpha/declcfg/write.go
  alpha/template/semver/README.md
  alpha/template/semver/major-version-demo.gif
  alpha/template/semver/minor-version-demo.gif
  alpha/template/semver/semver.go
  alpha/template/semver/semver_test.go
  alpha/template/semver/types.go
Labels: jira/valid-reference

#1076 Y streams for all
  alpha/template/semver/major-version-demo.gif
  alpha/template/semver/minor-version-demo.gif
Labels: approved, lgtm

#1056 opm render: update help text to mention that output is a stream to stdout
  cmd/opm/render/cmd.go
Labels: approved, lgtm

#1075 OPECO-2735: initial update to avoid nested docker execution
  alpha/template/composite/builder.go
  alpha/template/composite/builder_test.go
  alpha/template/composite/composite.go
  alpha/template/composite/composite_test.go
  cmd/opm/alpha/template/composite.go
Labels: approved, lgtm, jira/valid-reference

#1079 Add Support for Fetching Remote Catalog
  cmd/opm/alpha/template/composite.go
Labels: approved, lgtm
