Repository operator-framework/operator-registry, pull requests merged in 2024-08, with the labels that each got.

#1411 server_test.go: wait to run tests until listeners have started
  pkg/server/server_test.go
Labels: approved, lgtm

#1384 add optional schema migrations; default to olm.bundle.object instead of olm.csv.metadata
  alpha/action/migrate.go
  alpha/action/migrate_test.go
  alpha/action/migrations/000_bundle_object_to_csv_metadata.go
  alpha/action/migrations/migrations.go
  alpha/action/migrations/migrations_test.go
  alpha/action/render.go
  alpha/action/render_test.go
  alpha/template/basic/basic.go
  alpha/template/semver/semver.go
  alpha/template/semver/types.go
  cmd/opm/alpha/render-graph/cmd.go
  cmd/opm/alpha/template/basic.go
  cmd/opm/alpha/template/semver.go
  cmd/opm/migrate/cmd.go
  cmd/opm/render/cmd.go
  pkg/api/api_to_model.go
  pkg/api/conversion_test.go
  pkg/registry/registry_to_model.go
  pkg/registry/registry_to_model_test.go
  pkg/server/server_test.go
Labels: approved

#1412 remove 'automatically generated' strings from repo
  README.md
  bundles/etcd.0.9.0/manifests/etcdoperator.v0.9.0.yaml
  bundles/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  configmap.example.yaml
  manifests/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.0.yaml
  manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/api/conversion_test.go
  pkg/configmap/testdata/bundles/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/etcd/0.9.4/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_annotations_bundle/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_dependency_type/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_gvk_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_label_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_dependencies_bundle/invalid_package_dependency/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_annotation_name/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_bundle_2/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_crd/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_csv/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_sa/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/invalid_manifests_bundle/invalid_type/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/bundle/testdata/validate/valid_bundle/manifests/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/encoding/testdata/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/validation/testdata/invalid_bundle/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/validation/testdata/invalid_bundle_2/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/lib/validation/testdata/valid_bundle/etcdoperator.v0.9.4.clusterserviceversion.yaml
  pkg/registry/populator_test.go
  pkg/registry/registry_to_model_test.go
  pkg/registry/testdata/overwrite/etcd.0.9.0/manifests/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/overwrite/etcd.0.9.2/manifests/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.0/etcdoperator.v0.9.0.yaml
  pkg/registry/testdata/validPackages/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/server/server_test.go
  pkg/sqlite/configmap_test.go
  pkg/sqlite/directory_test.go
  pkg/sqlite/migrations/001_related_images_test.go
  pkg/sqlite/migrations/003_required_apis_test.go
  pkg/sqlite/migrations/005_version_skiprange_test.go
  pkg/sqlite/migrations/006_associate_apis_with_bundle_test.go
  pkg/sqlite/migrations/007_replaces_skips_test.go
  pkg/sqlite/migrations/008_dependencies_test.go
  pkg/sqlite/migrations/009_properties_test.go
  pkg/sqlite/migrations/010_set_bundlepath_pkg_property_test.go
  pkg/sqlite/migrations/011_substitutes_for_test.go
  pkg/sqlite/testdata/loader_data/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdoperator.v0.9.0.yaml
  pkg/sqlite/testdata/loader_data/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
Labels: approved

#1418 Update k8s dependencies to v0.31.0
  go.mod
  go.sum
Labels: approved, lgtm, needs-ok-to-test

#1417 model: validate unique bundle versions
  alpha/declcfg/declcfg_to_model_test.go
  alpha/declcfg/helpers_test.go
  alpha/model/model.go
  alpha/model/model_test.go
  go.mod
  pkg/api/api_to_model.go
  pkg/api/conversion_test.go
Labels: approved, lgtm

#1425 Update grpc-health-probe to v0.4.28 in Dockerfiles
  registry.Dockerfile
  release/goreleaser.opm.Dockerfile
  upstream-builder.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved, lgtm, ok-to-test

#1430 :seedling: bump alpine build images to 1.23
  registry.Dockerfile
  upstream-builder.Dockerfile
  upstream-opm-builder.Dockerfile
Labels: approved

#1433 :seedling: Update bingo + tools
  .bingo/Variables.mk
  .bingo/ginkgo.mod
  .bingo/ginkgo.sum
  .bingo/goreleaser.mod
  .bingo/goreleaser.sum
  .bingo/protoc-gen-go-grpc.sum
  .bingo/variables.env
  Makefile
Labels: approved, lgtm

#1432 :seedling: Bump ghcr.io/grpc-ecosystem/grpc-health-probe docker tag to v0.4.29
  release/goreleaser.opm.Dockerfile
Labels: approved

#1434 use dependabot for dockerfiles
  .github/dependabot.yml
Labels: approved
